# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "build"
    displayName: "Build the web application"
    jobs:
      - job: "build_job"
        displayName: "Build Job"
        steps:
          - script: |
              mvn clean package -DskipTests=true
  - stage: "test"
    displayName: "test the web application"
    jobs:
      - job: "test_job"
        displayName: "Test Job"
        steps:
          - script: |
              mvn test
      - job: "test_result"
        displayName: "Test result for jacoco maven plugin"
        steps:
          - script: |
              echo "always run this job"
              ls /target/surefire-reports/
            condition: always()

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/target/surefire-reports/*.xml'
            condition: always()
          