# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "build"
    displayName: "Build the web application"
    jobs:
      - job: "build_job"
        displayName: "Build Job"
        steps:
          - script: |
              mvn clean package -DskipTests=true
              ls -al
              pwd
              ls ./target/
          
          - publish: '$(System.DefaultWorkingDirectory)/target'
            displayName: 'Publish target folder for later use'
            artifact: dropScripts
          # - task: PublishBuildArtifacts@1
          #   inputs:
          #     PathtoPublish: '$(Build.ArtifactStagingDirectory)/target/'
          #     ArtifactName: 'drop'
          #     publishLocation: 'Container'
          # - task: Cache@2
          #   inputs:
          #     key: './*'
          #     path: '$(System.DefaultWorkingDirectory)/target/'
  # - stage: "test"
  #   displayName: "test the web application"
  #   jobs:
  #     - job: "test_job"
  #       displayName: "Test Job"
  #       steps:
  #         - script: |
  #             mvn test

  #         - task: PublishTestResults@2
  #           inputs:
  #             testResultsFormat: 'JUnit'
  #             testResultsFiles: '**/target/surefire-reports/*.xml'
  #           condition: always()
  #         - task: PublishCodeCoverageResults@2
  #           inputs:
  #             summaryFileLocation: 'target/site/jacoco/jacoco.xml'
  #           condition: always()
  - stage: "Docker_build_and_push"
    displayName: "Docker build and push"
    jobs:
      - job: "build_and_push"
        displayName: "build and push"
        steps:
          # - task: DownloadPipelineArtifact@2
          #   inputs:
          #     buildType: 'current'
          #     artifactName: 'drop'
          #     targetPath: '$(Pipeline.Workspace)'
          - download: current
            artifact: dropScripts
          - script: |
              printenv
              echo $(Build.SourceVersion)
              docker build -t val418orant/offers:$(Build.SourceVersion) .
              docker push val418orant/offers:$(Build.SourceVersion)

